//modify the first question by passing value of the parameter in square as pass by value,the parameters to find the area of the rectangle must be pass by address, the argument for area of circle must be passed by reference
#include<iostream>
using namespace std;
class figure
{
	int len,bre,side;
	double radius,pi;
	public:
		void area(int s);//pass by value
		{
			cout<<
		}
		void area 
}
